name=EEPROM24LCXX
version=1.0.5
author=Edward Blaha
maintainer=Edward Blaha <edwarda.blaha@gmail.com>
sentence=A lightweight library for interfacing with 24LCxx family I2C EEPROMs.
paragraph=This library allows for easy byte-wise and string-wise reading and writing to external EEPROMs using the I2C protocol on an Arduino Uno.
category=Data Storage
url=https://github.com/Edward-Blaha/EEPROM24LCXX
architectures=*AVR
includes=EEPROM24LCXX.h
